version: '3.1'

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mynab
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080